#!/bin/bash
BLUEC=$(tput setaf 4)
RESET=$(tput sgr0)
BACK=$(tput setab 7)

function BLUE () { echo "${BLUEC}${BACK}$1${RESET}"; }

BLUE "MISE A JOUR DU SYSTEME"
sleep 5
apt update -y
apt upgrade -y
BLUE "INSTALLATION DE SUDO"
sleep 3
apt install sudo -y
BLUE "AJOUT DE gbehra AU GROUPE SUDO"
sleep 3
usermod -aG sudo gbehra
BLUE "VERIFICATION DE L'AJOUT"
sleep 3
getent group sudo
BLUE "AJOUT DES PRIVILEGES A gbehra DANS SUDOERS"
sleep 3
sed -i 's/^# User privilege specification/a gbehra	ALL=(ALL) ALL/' /etc/sudoers
BLUE "INSTALLATION DE VIM"
sleep 3
apt install vim -y
BLUE "VERIFICATION DE LA VERSION"
sleep 3
vim --version
BLUE "INSTALLATION DE OPENSSH"
sleep 3
apt install openssh-server -y
BLUE "VERIFICATION"
sleep 3
systemctl status ssh
BLUE "CHANGEMENT DU PORT 22 EN 4242"
sleep 3
sed -i 's/^#Port 22$/Port 4242/' /etc/ssh/sshd_config
BLUE "VERIFICATION"
sleep 3
grep Port /etc/ssh/sshd_config
BLUE "REDEMARRAGE DU SERVICE SSH"
sleep 3
service ssh restart
BLUE "INSTALLATION DE UFW"
sleep 3
apt install ufw -y
BLUE "ACTIVATION DE UFW"
sleep 3
ufw enable
BLUE "VERIFICATION"
sleep 3
ufw status numbered
BLUE "CONFIGURATION PORT"
sleep 3
ufw allow ssh
ufw allow 4242
BLUE "VERIFICATION"
sleep 3
ufw status numbered
BLUE "REDEMARRAGE SSH"
sleep 3
systemctl restart ssh
BLUE "VERIFICATION"
sleep 3
service sshd status
BLUE "INSTALLATION DE LIBPAM-PWQUALITY"
sleep 3
apt install libpam-pwquality -y
BLUE "AJOUT DES REGLES MOT DE PASSE"
sleep 3
sed -i '/^password.*pam_pwquality.so retry=3/s/$/ minlen=10 ucredit=-1 lcredit=-1 dcredit=-1 maxrepeat=3 reject_username difok=7 enforce_for_root/' /etc/pam.d/common-password
BLUE "MISE EN PLACE DES REGLES DE DUREE DU MOT DE PASSE"
sleep 3
sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS 30/' /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS 2/' /etc/login.defs
sed -i 's/^PASS_WARN_AGE.*/PASS_WARN_AGE 7/' /etc/login.defs
BLUE "CREATION GROUPE user42"
sleep 3
groupadd user42
BLUE "VERIFICATION"
sleep 3
getent group
BLUE "AJOUT DE gbehra AU GROUPE user42"
sleep 3
usermod -aG user42 gbehra
BLUE "VERIFICATION"
sleep 3
getent group user42
BLUE "CREATION SUDO.LOG"
sleep 3
cd var/log
mkdir sudo
cd sudo
touch sudo.log
BLUE "VERIFICATION"
sleep 3
ls
cd ..
cd ..
cd ..
ls -a
BLUE "FIN"