#!/bin/bash
BLUEC=$(tput setaf 4)
RESET=$(tput sgr0)

function BLUE () { echo "${BLUEC}$1${RESET}"; }

BLUE "Mise à jour du système"
sleep 5
apt update -y
apt upgrade -y
BLUE "Installation de sudo"
sleep 3
apt install sudo -y
BLUE "Ajout de gbehra au groupe sudo"
sleep 3
usermod -aG sudo gbehra
BLUE "Vérification de l'ajout"
sleep 3
getent group sudo
BLUE "Ajout des privilèges à gbehra dans sudoers"
sleep 3
sed -i 's/^# User privilege specification/a gbehra	ALL=(ALL) ALL/' /etc/sudoers
BLUE "installation de Vim"
sleep 3
apt install vim -y
BLUE "Vérification de la version"
sleep 3
vim --version
BLUE "Installation de openssh-server"
sleep 3
apt install openssh-server -y
BLUE "Vérification"
sleep 3
systemctl status ssh
BLUE "Changement du port 22 en 4242"
sleep 3
sed -i 's/^#Port 22$/Port 4242/' /etc/ssh/sshd_config
BLUE "Vérification du changement"
sleep 3
grep Port /etc/ssh/sshd_config
BLUE "Redémarrage du service ssh"
sleep 3
service ssh restart
BLUE "Installation de UFW"
sleep 3
apt install ufw -y
BLUE "Activation ufw"
sleep 3
ufw enable
BLUE "Vérification du statut"
sleep 3
ufw status numbered
BLUE "Configuration des ports"
sleep 3
ufw allow ssh
ufw allow 4242
BLUE "Vérification des status"
sleep 3
ufw status numbered
BLUE "Redémarrage ssh"
sleep 3
systemctl restart ssh
BLUE "Vérification du statut"
sleep 3
service sshd status
BLUE "Installation de libpam-pwquality"
sleep 3
apt install libpam-pwquality -y
BLUE "Ajout des règles de mot de passe"
sleep 3
sed -i '/^password.*pam_pwquality.so retry=3/s/$/ minlen=10 ucredit=-1 lcredit=-1 dcredit=-1 maxrepeat=3 reject_username difok=7 enforce_for_root/' /etc/pam.d/common-password
BLUE "Mise en place de règles durée mot de passe"
sleep 3
sed -i 's/^PASS_MAX_DAYS.*/PASS_MAX_DAYS 30/' /etc/login.defs
sed -i 's/^PASS_MIN_DAYS.*/PASS_MIN_DAYS 2/' /etc/login.defs
sed -i 's/^PASS_WARN_AGE.*/PASS_WARN_AGE 7/' /etc/login.defs
BLUE "LA PREMMIERE PARTIE EST FINIE, REBOOT VM PUIS LANCER LE DEUXIEME SCRIPT"