#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "Ce script doit être exécuté en tant que root."
  exit 1
fi

BLUEC=$(tput setaf 4)
RESET=$(tput sgr0)
BACK=$(tput setab 7)

function BLUE () { echo "${BLUEC}${BACK}$1${RESET}"; }

BLUE "INSTALLATION DE LA PARTIE BONUS"
sleep 5